### ISSUE TITLE
Handle ACRO-checked outputs of types that we don't know how to display

### ISSUE THREAD

**Issue by benbc** [opensafely-core/sacro#118]
In order to allow for evolution of the ACRO tool, we should helpfully handle the addition of new checks for types of outputs that we haven't seen before. Even if we don't know how to display them, we should show the pass/fail status and any other details correction, and allow output checkers to accept or reject them.

Note that this is related to (but separate from) #117.

**Comment by lucyb** [comment]
I have tested this by editing my `results.json` and amending the "custom_jfif" section to make it look like it's been processed by acro

```
    "custom_jfif": {
        "uid": "custom_jfif",
        "status": "pass",
        "type": "exciting_new_thing",
        "properties": {},
        "command": "results = acro.new_command(y, x)",
        "summary": "pass; dof=12958.0 >= 10",
        "outcome": {},
        "output": [
            "XandY.jfif"
        ],
        "timestamp": "2023-06-29T17:02:52.348950",
        "comments": [
            "This output is an image showing the relationship between X and Y"
        ]
    },
```

This resulted in the following. It correctly shows the ACRO status and I can approve or reject like any other ACRO output. However, it says the output type is "Unknown", which is the same as the custom outputs. I think this is probably desirable, but I'd like to check? I'm wondering if the output type of the custom outputs should be "custom" instead?

Otherwise, does this all look okay?

![Screenshot from 2023-07-07 11-00-36](https://github.com/opensafely-core/sacro/assets/3889554/578c207a-1a71-45b8-afa5-011d09353b8a)

**Comment by benbc** [comment]
@lucyb I don't think that's quite right. The output type should be `exciting_new_thing`. The reason it's not is that the code switches on the presence of the `method` property (IIRC), which you haven't included in your faked JSON. In your case I think it would end up being `new_command` (we used to parse this out of the code in `command`, but we don't have to do that any more).

**Comment by lucyb** [comment]
@benbc ah, I see now (I hope). So, if I update the JSON to have this:

```
        "type": "new_type",
        "properties": {
            "method": "new_method",
        },
```

Then the output type that's shown is "new_method new_type", both in the menu and in the summary. I can't see anything relying on a known list of types/methods. Is that okay?

![Screenshot from 2023-07-07 16-49-10](https://github.com/opensafely-core/sacro/assets/3889554/262c75fe-a9a4-4c17-bbf7-16974baaa42a)

**Comment by lucyb** [comment]
In that case, are you happy that I can close this ticket?

**Comment by benbc** [comment]
Yup.
