### ISSUE TITLE
User documentation for end-to-end walkthrough

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/sacro#82]
There should be enough documentation in this repo for a knowledgeable user to easily walk through the flow outlined for the walking skeleton:

- [ ] Start with a pre-canned set of simple non-disclosive crosstab outputs and an associated ACRO JSON file
- [ ] Download and install the standalone ACRO-viewer on Windows
- [ ] Run the ACRO-viewer and open the ACRO JSON file
- [ ] See “pass” indicator for each output in ACRO-viewer
- [ ] Approve the outputs
- [ ] Save the zip file containing the outputs and ACRO report into a location of your choice

Note: The instructions (and the pre-canned outputs) should cover the functionality that currently exists. We expect that these instructions (and the pre-canned outputs) will updated as we go along to cover most of the functionality that we implement.

**Comment by benbc** [comment]
@lucyb Great, thanks. I'd like to set an expectation that these instructions (and the pre-canned outputs) are to be updated as we go along to cover _most_ of the functionality that we implement. Perhaps it's helpful to mention that context in this issue so that the person working on it understands that this isn't an ephemeral thing.
